"""Shared Pydantic models for the coding agent."""

from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field


class FileSnapshot(BaseModel):
    """A small representation of a source file in a repository."""

    path: Path
    content: str

    model_config = ConfigDict(frozen=True)


class RepositorySummary(BaseModel):
    """A compact summary of files relevant to an agent request."""

    root: Path
    files: list[FileSnapshot] = Field(default_factory=list)

    model_config = ConfigDict(frozen=True)


class Patch(BaseModel):
    """A unified diff generated by an LLM or another patch source."""

    diff: str = Field(min_length=1)

    model_config = ConfigDict(frozen=True)


class CommandResult(BaseModel):
    """The captured result of a local command execution."""

    command: tuple[str, ...]
    return_code: int
    stdout: str = ""
    stderr: str = ""

    @property
    def succeeded(self) -> bool:
        """Return whether the command exited successfully."""

        return self.return_code == 0


class AgentRequest(BaseModel):
    """User intent and execution preferences for one agent run."""

    instruction: str = Field(min_length=1)
    repository_path: Path
    test_command: tuple[str, ...] | None = None
    max_fix_attempts: int = Field(default=1, ge=0, le=5)


class AgentResult(BaseModel):
    """Final outcome from a coding-agent run."""

    request: AgentRequest
    summary: str
    patch_applied: bool
    test_result: CommandResult | None = None
    fix_attempts: int = 0
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )


class ActivityRecord(BaseModel):
    """A user-facing record of non-mutating UI activity."""

    activity_type: str = Field(min_length=1)
    repository_path: Path
    title: str = Field(min_length=1)
    summary: str = Field(min_length=1)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
